### ISSUE TITLE
Installation failing at 43%, url appears to be broken

### ISSUE THREAD

**Issue by Ariel1524** [Insidious611/DancingMadFF6#106]
At about 43% during the installation a URL turns up a 403 error page. Sounds like one of the mirrors may be down

**Comment by Dizzy611** [comment]
If you have a full installer log so I can see which URL is failing I'd appreciate you attaching it. If you're on windows it should be in %userprofile% as dancing-mad-installer.log

Two of our mirrors are currently down because I'm working on moving to a new hosting provider and having some routing issues, but the Amazon S3 mirror should be covering for them so the fact it isn't is worrisome.

**Comment by Dizzy611** [comment]
Just wanted to let you know that our main mirrors should be back up now. Apologies for the chaos.
