### ISSUE TITLE
Missing track?

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#11]
Track number 25 (hex 19) "Wild West" is absent from all the download sections, though in your download location http://www.somebodyelsesproblem.org/ff6data/ (I dug through the scripts to find the URL, it's made it much quicker sorting through the songs when I don't have to check if it's a duplicate of the OST track) sideselections document, you mention picking the SSC one.

In the SSC folder you have track 19, which contains the song data to wild west (so it's numbered with the hex for some reason, since track 19 is techno de chocobo, which SSC doesn't have a remaster of).

I was wondering why there isn't a track for Wild West, along with the 7 "disabled" tracks in the OTH folder? Some type of coding problem implementing them?

**Comment by Dizzy611** [comment]
wild west is an odd one, I don't  remember having any issue with that in
testing so I'll have to take another look. it's entirely possible that I
simply screwed up going back and forth from hex to decimal at some point.
the other disabled things, see issue #3. the Opera has issues with timing.
Specifically, the code used to time the opera to Celes's vocalizations in
the game is much more complex than the rest of the music code in the game,
and simply replacing it the way I replace all the other tracks (by hooking
the "play this music" call to the SPC) causes the game to hang at that part
in the Opera where she's supposed to start singing. I thus stubbed the
Opera code out until I could find the time to figure out how to get around
that particular issue.

**Comment by edale2** [comment]
Well you don't have the audio data for Wild West in any of the other albums, and it's only in SSC because it was mislabeled.

IIRC that's the song that plays on the Veldt (Velt? the place you get Gau and learn his rages), maybe it had a bad interaction with Gau's theme or something?

BTW, do you know which of the 6 patches from Rodimus Primal's Ted Woolsey Uncensored retranslation patch was used there? I'm guessing the basic one + updated opera should be fine, but does the bug fix one cause any problems? I know the music player one is right out, lol.

**Comment by Dizzy611** [comment]
Unfortunately I don't know. The user who reported the issue was on the qhimm.com forums (where I originally posted the thread about this project in the early early days). I've only tested this patch on its own myself, though I suspect anything that does not modify the SPC code (or change where the SPC code is located within the ROM, since changing that would break my override) is likely to work, unless it happens to by complete chance overwrite the specific usually-blank section of the ROM I've stuck my MSU-1 handlers in.

**Comment by edale2** [comment]
Eh, once I get the soundtrack worked out how I want it I'll try testing it out. I had forgotten just how bad the original localization was, given I've played so many remakes and mods. I'll report my results. it'll likely be a week or two though.

**Comment by Dizzy611** [comment]
Looking at the old Readme doc from back when the project first started I can see exactly where the mixup happened. Track hex 25 (decimal 37) goes unused because it's a random  fanfare which we don't have any replacements for. So, like with some other sounds that are just sound effects, we skip it because it's something we want to play on SPC. 

Somehow, when building the pack for release, I read this as track 25 (decimal) being one that we skip, and simultaneously when converting SSC track 25 (decimal) to PCM, it was assigned to track 19 (the hex for 25).

Quite the weird mixup, and surprised this is the only track it happened to. Thankfully, I *should* have a copy of the PCM files from before they were renamed from CD order to ingame order on my OneDrive, which should have the missing OCR and OST wild west PCMs. If not, I may ask you to consider recreating them for me if you have time.

**Comment by Dizzy611** [comment]
Having looked at the batch file used to rename PCM from CD to in game order (referenced in above commit) it's even simpler than that. Before the above commit, it simply renamed both wild west and techno de chocobo both to ff3-19.pcm instead of the earlier one being renamed to ff3-25.pcm. The effect is noticeable on SSC specifically because it's the only set that has a wild west but not a techno de chocobo

**Comment by Dizzy611** [comment]
And that commit explains why I never caught this through the installer. I must have copied the track numbers from the batch file directly when making the mapping for the installer, so it makes the exact same "random hex conversion and duplicate entry" mistake, and because tracks are processed in CD order (due primarily to the custom selection dialogue box) the issue hides itself the exact same way.

Good catch.

As to why I didn't catch this during initial testing... During my play through testing I renamed tracks manually as the installer and distribution batch file both hadn't been written yet, and when testing the installer I generally just make sure the game plays fine up until after the first boss as that can be done quickly.

So a perfect storm of random factors.

Once I've found or recreated and reuploaded the missing data and then installed and tested (probably find a srm on the veldt) I'll close this issue as fixed.

**Comment by edale2** [comment]
http://fantasyanime.com/finalfantasy/ff6/ff6saves.htm

Should be able to use one of those. Saves at various parts of the game.

**Comment by Dizzy611** [comment]
Have found the missing tracks for OCR/OST :)

**Comment by Dizzy611** [comment]
Have tested SSC/OCR/OST versions of Wild West as now working ingame on my copy, proper looping included. 
The OCR version is such a weird choice in terms of Genre. Kind of... rock dubstep? I'm really not sure what to think about it, and I definitely understand why I didn't choose it... :P

I might be able to fix this one as a hotfix before the other major installer revisions as it's just a matter of replacing TrackMapping.dat and uploading the missing tracks/renaming the misnamed SSC track.

**Comment by Dizzy611** [comment]
Files uploaded and hotfix released. Closing this issue as now officially fixed :)
