### ISSUE TITLE
Provide minimal prepack for using other MSU-1 tracks

### ISSUE THREAD

**Issue by InquisitiveCoder** [Insidious611/DancingMadFF6#114]
It'd be really convenient if the Prepacks section had a zip that only contains the four cut tracks (90-93) for users that want to use other soundtracks (e.g. Pixel Remaster.) Currently both the installer and the Prepacks will force you to download ~1 GB worth of tracks that will then be discarded in that use case.

**Comment by edale2** [comment]
https://bigfuckin.rocks/ff6data/contrib/CSR/
That has the tracks and IPS patch for the cut song restoration mod.

https://mega.nz/folder/PJZg1IRb#kS3ECIgKhAkc-qHWkVGRAg
This has a zip with just the CSR files, as well as a zip with the version of the music player mod customized for Dancing Mad (both the normal one and the one including the cut songs in the playlist).

Also, in the track selection of the installer, there's an option (I think it's labeled "SPC", since that's the SNES native audio format; but it might be "don't download"... it's the far right option) you can select to have the installer not download that track, so you can set it to only download the ones you want.

**Comment by Dizzy611** [comment]
For reference it is indeed "SPC", and selecting that for any tracks you don't want is the preferred way to install just the patches and CSR/etc without installing the rest of it.

I could distribute a prepack with just the cut songs restoration, but I already distribute an IPS for the main Dancing Mad MSU-1 patch and the CSR stuff is in the above-linked folder, so given how few people will be interested in such a thing I'm honestly not super inclined.

**Comment by Dizzy611** [comment]
Closing this wontfix as edale has provided the solution I want to advocate for for the moment. The installer will however have a "Patch Only" selection in the rewrite.
