### ISSUE TITLE
Installer on Linux running on Cinnamon shows "SNES ROMs" three times for different types, does not show extension. 

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#118]
Combine into single, multi-accepting type?

**Comment by hazelshantz** [comment]
perhaps. anyways, I just want to note that your windows 32 bit installer can be ran under arch linux with the help of wine. I may do further testing later when my optical fiber internet comes back, as I'm running off a mobile hotspot for the moment due to heavy thunderstorm. 
I want to test all your packs so I can find the one that I like the most. 
I already tried running your tar.gz code but it fails to run for some reason. later I'll make a proper issue tracker.

**Comment by edale2** [comment]
@lunelovehearn 
There's a few music packs that haven't made it into the installer yet, you can find those here:
https://www.zeldix.net/t1335-final-fantasy-vi-j-final-fantasy-iii-us

Also ChrystalChameleon has recently been releasing more FFVI songs, and I've been converting them as she releases them (she's only a few tracks away from finishing the entire soundtrack), they likewise aren't included in the installer yet, you can find those tracks here (there's links to the youtube video for pretty much all of them, so you won't need to download them all to check them):
https://github.com/Dizzy611/DancingMadFF6/issues/115

**Comment by Dizzy611** [comment]
Somewhat fixed by the new installer, which now just prompts for All Files because I couldn't get filtering to work. May revisit later.
