### ISSUE TITLE
OCR track 34 contains both the data for track 34 and what sounds like the opera

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#12]
![screenshot - 10_4_2017 9_39_46 pm](https://user-images.githubusercontent.com/20962345/31207505-960e220a-a94c-11e7-81f5-0a62f17d278f.png)

The first chunk is the track 34 data, after the silence, at about 2:45 on the timeline, what sounds like it might be the opera starts.

-edit- looks like it's actually the OTH track,

**Comment by Dizzy611** [comment]
Interesting. The "OTH" tracks were added kind of last minute when the person who did the editing for most of the audio, Covarr, decided iirc that the OCRemix versions of the Opera and related tracks (the only version we had other than the OST at the beginning) didn't really fit in with the game as well as he'd hoped.  So it's possible we missed something when working on them. I'll have to open that file up in Audacity myself and see if I can figure out what happened there

**Comment by Dizzy611** [comment]
Still don't know how this happened, but confirmed and fixed (locally, anyway. I'll upload the fixed stuff to my server as one big batch once I'm finished with all of the fixes/changes to the audio files). 

At first I tried editing it in audacity and while that preserved the header (since I didn't do anything to the couple of random samples it interpreted the header as being, just deleted the irrelevant data at the end) it somehow changed the audio (not perceptibly, but the samples were different in a hex editor and the waveform had a very slightly different shape) so, not wanting to change things unnecessarily, I instead took a look at the resulting file and, based on where it ended combined with where the silence started in the broken file, used the hex editor to chop the ff3-34.pcm file down to the right length. I also tested the loop point to make sure it was still correct (it is).

So consider this one done and dusted. :)
