### ISSUE TITLE
ROSE: Black screen in combat on FXPak Pro

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#122]
Reported by Tomume on Discord. This may be an issue with in-game hooks, am asking for further details. ROSE patch appears to have been applied after Dancing Mad per my recommendations.

**Comment by tomume** [comment]
hi bro. i wanted to correct myself because i made it to work ! so here are the steps: ff3 us v1 no header. run dancing mad, apply music choice but do not apply optionals. then patch the rom ff3.sfc with rose NH. Here is my result :)
![Capture](https://github.com/user-attachments/assets/346176cf-5ccc-401e-be90-9d7e49d9c813)

thanks a lot and take care !

PS: if i dont disable in game hooks, the game shows heavy glitches in the equip menu. dunno if fixing checksum with Advanced_SNES_ROM_Utility can change somehting...

**Comment by Dizzy611** [comment]
Just saw this comment. Thanks for the further explanation! Going to close this as not a bug, as it sounds like you tried to combine optional patches with ROSE, which I can't really do anything with the optional patches breaking compatibility (it's not my code for all of those).

Regarding the equip menu thing with ingame hooks, that's a known issue I've talked with the FXPak Pro people about. It's pretty much an unavoidable problem due to the in game hooks effectively using all the spare CPU time during the nmi, leaving no room for my code. So disabling them is recommended.

Again, thanks for the update, sorry it took me so long to see this.
