### ISSUE TITLE
Got a new version of Decisive Battle for you!

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#14]
Damn it was hard to find a place it was possible to loop this thing. There's a slight click on the loop, but you can only really hear it if you're listening for it (it was impossible to get both tracks on a nul crossing at the same time anywhere in the repeating chord). Kinda offends my CDO (it's like OCD, but in alphabetically order... as is proper) perfectionism, but it's literally the best I could do.

So now, with no further adieu let me present to you, The Black Mages' version of The Decisive Battle, Fully converted to MSU-1 compatible PCM looped audio!

https://mega.nz/#!mZRCRDKA!5O9lfPD0Hg7We1qLQAYVEjMdgArg82TQZYNvpmsFqTU
(I actually tested the looping before posting this time even!... Now that I figured out how)

Oh, the full volume one actually drowns out the sound effect of the cursor moving (seems like a good way to test the volume vs in-game sounds for equalization), so I'd really recommend the deamplified one.

---

*edit- OK, after some more testing to match up the volume of the song to the in-game sound effects, I have a further deamplified copy of this, turns out -7.5dB really does seem to be the magic number for this project (deamped version in above link was a -6dB, this one's -7.5dB).

This is only the corrected deamp, for the full-volume one use the above link.
https://mega.nz/#!GR4TQZoY!vBjD8zwc86SarWvUVlSlUwBiDVVdqf4aBiOHdfdCIFE

**Comment by Dizzy611** [comment]
Looking at this, I can definitely understand why looping this was difficult, with the exception of the intro the entire track is a complete solid wall! Little wonder it's drowning out the cursor movements. It sounds amazing though. Definitely popping this one into the OTH folder in my local working copy.

I can barely hear the click you're talking about on the loop but honestly given the fact I've not got fading working yet the patch is going to have its share of barely-noticeable pops and clicks anyway, and even once I've got that working, as you said, it's the best you could do.

Accepted and staged for upload later.

**Comment by edale2** [comment]
You think that's amazing? You should hear their version of Dancing Mad.
https://www.emuparadise.me/soundtracks/highquality/download/Final_Fantasy_-_The_Black_Mages/FLAC/09_-_Dancing_Mad_(Final_Fantasy_VI)/1483

Unlike the OCR one, it actually still sounds like Dancing Mad, while being infinitely more awesome (and 12 minutes long).

I'd consider trying to turn that into PCM's as well, but I understand there's some problems getting Dancing mad to work right? and I'm not sure how the track would need to be setup given it appears Dancing Mad was split into 3 separate tracks.

**Comment by Dizzy611** [comment]
Dancing mad should work fine (the noted problems were fixed before the beta using a dirty, dirty hack), but yeah, it requires splitting into multiple different parts for switching between during battle (due to it using different parts of the song for different stages of the kefka battle). There are actually iirc 5 parts involved, though due to one part being relatively short and only being played directly before another without any battle stage switching involved, I was able to shrink it down to 4. 

Parts 1-3 are redirected from track 0x3b (ff3-59) to otherwise unused 0x65, 0x66, and 0x67 (ff3-101 ff3-102 and ff3-103) by the code. Afaict the original SPC in the ROM had 3 subsongs and some magic for switching between them. I've basically hooked said magic in the ASM and redirected it to play each part individually when needed.

Parts 4 and 5 on the other hand are seperate tracks (0x52/ff3-82 and 0x50/ff3-80 respectively), and I've used the normal ingame track numbers. However, I stuck Part 5 onto the end of Part 4 for reasons outlined above, and when the game requests Part 5 I simply tell it to ignore it and continue playing Part 4.

The only remaining issue with Dancing Mad from my testing is one that's probably impossible to fix: The original game played to the end of a part before switching them. This isn't possible on MSU-1 afaict, due to being unable to switch from "looping" to "not looping" in a playing track, or reliably tell when a "not looping" track has ended. Thus, the switches are made instantly.

**Comment by edale2** [comment]
So I have to split Dancing Mad into 4 parts, and loop each part individually?

Hmmm... Gonna have to grab the OST version of Dancing Mad and compare it to where you split and looped your files to get this to work (that final boss battle god mode save from that page I linked you to will be pulling it's weight on this one).

So to be clear:
Dancing Mad part 1: ff101.pcm
Dancing Mad part 2: ff102.pcm
Dancing Mad part 3: ff103.pcm
Dancing Mad part 4: ff82.pcm
?

**Comment by Dizzy611** [comment]
Looks right to me.

**Comment by edale2** [comment]
I think I'll focus on checking for any more exceptions to the -7.5 dB deamp before trying to tackle Dancing Mad. Who knows, I may get inspiration for another edit like the phantom train ambience while doing it, now I have _options_. 

*edale2 begins cackles maniacally.*

Though honestly, I don't really think there are many/any other parts that could work well with an ambient sound edit. I might find a track like OCR 76 that needs an intro/outro removed though.

**Comment by edale2** [comment]
Actually, now that I think of it... Which track plays while you're on the raft with banon, in the area where you first meet Ultros? If that track doesn't play anywhere else, some nice white-water rapids ambient sounds might work well...

*edit-tracked down a youtube video of that part of the game, there's no music playing at all, just an ambient sound effect of the water. Oh well.

**Comment by edale2** [comment]
Hmmm...Looks like the raft sounds effects are stored in 3C (track 60), since there's no music playing to conflict with it, can I just find some decent white-water rapids sound effects convert to PCM, name ff3-60.pcm and I'm good to go? Or would you need to add some code to the hack to enable MSU-1 on 3C?

**Comment by edale2** [comment]
Tested throwing something on track 60, didn't work, I'm guessing you'd need to modify the hack?

If you add it to the hack, I'll be glad to find a track or three to use in that slot. No need to go out of your way if it's something difficult to do.

Already got a few decent candidates:
https://www.youtube.com/watch?v=KRg0vHytUzg
https://www.youtube.com/watch?v=w9qpsiQvI2c
https://www.youtube.com/watch?v=hreXu8827ho
https://www.youtube.com/watch?v=_RPjndlY-sc
https://www.youtube.com/watch?v=w9qpsiQvI2c

I think the top 2 are the best personally. (I'd obviously be looking for higher fidelity than a youtube mp3 rip, but honestly, for this kinda sound, a little bit of white noise is only gonna help, lol)

**Comment by Dizzy611** [comment]
I've not done much with the sound effects tracks as they're something I skipped on purpose
That said if it plays them the same as it plays everything else your drop in should have worked.
I know from an earlier mistaken thing during early early pre alpha that replacing the wind sounds in the opening with music will play the music.

Unless I specific stubbed that track out in the code... I'll have to check again. I did that with some sound effect tracks due to minor bugs.

**Comment by Dizzy611** [comment]
Nope. No references to track 3C in my code. Weird, it must be using a different routine to play the track.

**Comment by edale2** [comment]
I'll have to try some of the other effects track numbers then, maybe it's just mislabeled in your notes.

**Comment by edale2** [comment]
OK, I found the Raft track, it's track 30 (1E), which you have labeled as "Rain Effect."

I'd assume 5C (track 60) is the actual rain effect.

**Comment by edale2** [comment]
Nice, one of the tracks I found sounds almost exactly like the in-game sound. Which fits given it was recorded by a river in a canyon, lol. (I'm thinking that one would go with the OST set of tracks)

I'm gonna take another 20 min or so looping for potential tracks, then I'll convert the best 3-4. Gonna test them all in-game, so maybe 2 hours before I have some tracks uploaded.

**Comment by Dizzy611** [comment]
So this is one where if I didn't absolutely love train suplex (the OCRemix track) you might have changed my selection, because it is really good, but I dunno, I just love the sound of the OCR version. Admittedly, however, that may be partly from the fact that back when the very first parts of the game were all I could get working, in the very beginning of the project, the fight with whelk and hearing that song come blasting out was the first taste of how this could really enhance and change the game :P.

That said, I'd consider this a close second.

**Comment by edale2** [comment]
OCR version is a good version of Decisive battle, nothing wrong with sticking with it, I prefer this version though. :)
