### ISSUE TITLE
No Ending Credits!

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#26]
I don't know if this is just in the patch from a few hours ago, or if this has been in there for a while, because I never took beating Kefka to test Dancing Mad into the credits.

Once you beat Kefka, the ending stuff starts to play, magic starts leaving the world and all that, then it gets to the bit where it shows a book with it's pages turning (around where track 83 starts playing), and the book bit fades out and.... it just stays on a black screen with the MSU-1 music playing.

**Comment by Dizzy611** [comment]
This sounds like it might be similar to the opera bug, where it's trying to manipulate the SPC behind the scenes and because I told the SPC to load nothing, it hangs. The fix to the opera bug was essentially to tell it to "play" the SPC music at 0 volume in the background, to give the code something to mess with. 

If it is, a workaround should be simple but between the opera issue, the Figaro->Sabin>Figaro bug, the sleeping bug, and this they all point to the idea that setting the SPC to play "track 51" (silence) might be the wrong tactic.  I may have to try rewriting that entire section of my code. I'll put in a workaround first to see if that fixes things. 

Will give that some thought and time in the morning.

If I'm right, this should be a quick fix for at least a workaround to get it to stop freezing.

EDIT: Actually, quick test you can do, to help make sure I'm on the right track: If I am, you should be able to get past that bit by deleting the tracks for the ending from the folder, forcing it to play the original SPC music for the ending.

**Comment by edale2** [comment]
ok, giving it another quick (20 min or so) runthrough of the final boss to see if it hangs with track 83 gone.

**Comment by edale2** [comment]
Yep, deleting track 83 lets the ending continue normally.

**Comment by Dizzy611** [comment]
Alright thanks. When I get back to coding and such in the morning that
gives me a good idea of where to start.

**Comment by Dizzy611** [comment]
Alright, I've fixed the freeze, but I now have an issue where it continually restarts the credits theme each time the credits switches scenes, so we're getting there but not quite.

**Comment by Dizzy611** [comment]
Ffff... I've figured the second bit out. The ending is the *one* area in the game where the memory location I use to record what track was last playing gets overwritten by the game code. It's used to store the high-res graphics used in the ending scenes, and that causes my code to think it's not playing the track it's playing.

There's an easy workaround but it's kind of funny, nonetheless.

---

Off topic but I gotta say, having played Kefka's final battle 3 times now (because for some reason I keep forgetting to save a save state right before the credits >.>) I love the line "You sound like chapters from a self-help book!"

**Comment by edale2** [comment]
Relevant to your off-topic comment:
https://www.youtube.com/watch?v=6ldAQ6Rh5ZI
:p

And I think I played through Kefka's final battle like 8 times yesterday, lol.

I haven't been using savestates, to avoid any bugs caused by them (rule number 1 of bug testing, remove as many variables as possible to get the most reproducible results).

**Comment by Dizzy611** [comment]
Absolutely true. There was actually a point recently when testing where I thought using a save state had screwed me up (It hadn't, but it's certainly possible).

I'm waiting for what would normally be "Ending part 2" to start to be absolutely sure, but I think this bug has finally been fixed. I'll push the fixed code when I'm certain.

**Comment by Dizzy611** [comment]
Yep, it gets all the way to the "The End" screen, where it stays on that and plays the prelude forever. Pretty sure that's normal, supposed to basically tell you "Shut off your console or reset it, we're done". Pushed, committed, and closed! That was more complex of a bug than I was expecting, but we got it done.

**Comment by edale2** [comment]
OK, I'll be honest, l haven't really worked on this today, crappy day at work and other factors just didn't leave me in the mood to do much.

That said I'm giving the ending a quick runthrough to verify your fix is working before i go to bed, and I got to wondering, when you first enter the boss, as Kefka's givig his whole "I knew you would come..." intro, there's a weird song playing with lots of weird warped effects... It's definitely SPC sound and not PCM... What track # is that?

**Comment by edale2** [comment]
-Note to self, check timing of OST track 83, a second or two of silence may be need to be added to the beginning. Need to do a check of the ending on an unmodded ROM. Thankfully it's not looped, so I won't have to worry about relooping it.

**Comment by edale2** [comment]
Well that's that. asides from the slight timing issue I *may* have found, ending works as advertized. And yea, I'm pretty sure the looping of Track 1 is how it's supposed to go, but I'll double-check when I do my unmodded ROM runthrough tomorrow.

Gotta be up early tomorrow, so going to bed now (god, how messed up is my sleep cycle that I consider 4AM going to bed early?).

**Comment by Dizzy611** [comment]
Dunno about that weird track. I've noticed it before during testing and noticed that, even though I have every piece of music covered, it still plays via SPC. I assume they're doing something screwy in the code to synthesize that warping effect and because of that they're skipping the normal track loading routines.

As to timing on OST version of the ending, you're probably right on it being off slightly, I've not tested the ending using it, my recent testing has all been with the OCR version.

**Comment by edale2** [comment]
Yea, timing is definitely off, right from the very first track, need to add some silence to the beginning.

Gonna need to find a stopwatch for this one...

**Comment by edale2** [comment]
That feeling when your first edit, that you were expecting to have to add/remove a bit of the silence you put into it, turns out to be perfect to the microsecond.

Then when it's at about 80% uploaded, and you're about to post the fixed audio... You notice the 2nd half is still a few seconds off.

Fuck.

Turns out in the OST instead of properly ending part 1 before starting part 2... They cross-faded into the second one.

Added a fade-out/fade-in, and extended the silence this made between them by 2 seconds. Testing the fix now, I hope it's close, because I have to sit through 12 minutes of ending to check each time...

**Comment by edale2** [comment]
Sigh... Extending to 4 seconds between tracks and trying again...

*edit- And we're up to 6 seconds, do I hear 8?

**Comment by Dizzy611** [comment]
I just have to say I commend your dedication to helping this project and
doing things with precision, it's really awesome to see people with as much
passion for this project as I have. Thank you.

**Comment by edale2** [comment]
Yea, the trick is to not bash my controller through my TV when I pass the moment I'm checking the timing on the second half against THREE FUCKING TIMES, because I'm distracted doing other stuff while the 12 minutes of ending plays...

**Comment by edale2** [comment]
DONE!!!

https://mega.nz/#!yERgwT4Z!tuxTA1uurh4RdU-ApXs7j8vZ0-nvf35hneftjpcWmyA

Correct timing (or at least close enough to not matter enough for me to fix) was around 5.5 seconds between tracks. In addition to the 3.6 seconds added to the beginning of the track.

Already normalized.

I'll start working on the Opera stuff next, but not tonight.

**Comment by edale2** [comment]
OK, I lied, insomnia's flaring up, so I did something quick and easy.

The waves sound that plays on Solitary Island (first island in WoR) doesn't play with any other music, the 2 scenes on that island with music, the waves sound cuts out as the music starts.

Wave sounds = track 58.

Tested quickly with one of the raft tracks and works perfectly.

Only thing left to check is if there;s any music when you first wake up there, after the destruction of the WoB. Don't feel like sitting through a crapton of cutscenes atm.

I'll take care of the opera stuff before finding and converting some wave sounds. Gonna be really picky on them though, gotta be the type that just conveys the feeling of desolation, of an absence of life. Means among other things, absolutely no animal noises in the background.
