### ISSUE TITLE
Final Beta testing progress.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#36]
Using this issue to keep track of current testing progress/environment for Final Beta, and any minor issues I encounter so that they can be made into proper issues later.

Testing environment: Raspberry Pi 3, RetroPie, lr-snes9x compiled from source. 

Song selection: Developer's Recommendation + Raft scene (ff3-30-3, haven't switched to -OST yet) + Waves, installed with current installer.

Current progress: Sabin's scenario, Veldt, just named Gau.

Minor issues encountered thus far:

1. "Select a scenario" area with the moogle continues playing raft scene "music" until you enter and exit a menu, at which point it plays silence. Need to test to see what it does in unmodified game.

2. Minor hitching (stuttering/sound interruptions) when playing on Pi, suspect minor framerate issues. Seems to exist in unmodified FF6 as well, likely nothing to do with my patch.

Existing bugs encountered: #4 (but the workaround is still working, and I have not yet encountered another scene like this after the sabin-naming scene in Figaro), #5 (obviously)

Existing bugs not encountered: #17 (yet. But I've stayed at numerous inns and used various tents, so I'm hopeful)

**Comment by Dizzy611** [comment]
On a somewhat off-topic note, it's kind of nice hearing this playing through my TV, which is part of why I decided to use a Pi for testing. Ideally I'd like to use an SD2SNES with my SNES, hopefully I can save up the money for one eventually.

**Comment by Dizzy611** [comment]
Current progress; Completed sabin scenario, completed most of Locke scenario, left South Figaro, on way to Narshe.

New minor issue (actually not that minor as it's extremely annoying :/):
 3. The world map after leaving South Figaro in Locke's scenario does not have a set theme song, instead playing the last song played (usually the sneaking-around-theme, I forget what it's called). However, because of the way my code works, after battle it thinks the last song played is the victory theme, so after your first battle upon leaving South Figaro, it just plays the victory theme over and over again on the world map until you change to a map that *does* have a theme song.

**Comment by Dizzy611** [comment]
Note on Minor issue 3: Entering and leaving the cave leading from south figaro causes the world map to behave normally (playing Terra's Theme as most non-airship WoB world map bits do). It's only the trip from leaving south figaro to the cave that seems to set a flag to "continue playing the last song"

As the victory or battle themes should *never* be songs we resume, an easy fix (and probably the best fix) to this would be to never set LastTrack if we're playing battle or victory music.

**Comment by Dizzy611** [comment]
Current progress: Reunited party. No new bugs encountered, save for a reoccurrence of minor issue 1 after completing Locke's stage. It played the cavern theme instead. I'm thinking this may be our sole use of Track 51 in the actual game, but I'll have to run this in a debugger to be sure, that's just a guess, and wouldn't explain why entering and exiting the menu fixes the issue (if the moogle scene is playing track 51, entering and exiting the menu should just cause the track to start over)

I'm going to leave it here for today, and open new issues for minor issues 1 and 3, but I'll get back on this playthrough tomorrow.

**Comment by Dizzy611** [comment]
Have now made seperate issue reports for both pertinent minor issues. Further information/progress on these bugs will be continued there.

**Comment by edale2** [comment]
That minor sound hitching is because the Pi3 isn't powerful enough to properly emulate the SNES (which needs a 3GHz processor to do!!! from a 58MHz system!!! architecture differences can be a bitch), and is perfectly synced up to framerate slowdowns.

Nothing can be done about this.

**Comment by Dizzy611** [comment]
I figured as much. 

Current progress: At Kohlingen after Terra's "disappearance". No new issues encountered.

**Comment by Dizzy611** [comment]
Going to be getting back into this tonight, took a couple days off

**Comment by Dizzy611** [comment]
Current progress: At Albrook after the Opera

My fiancee was pretty impressed with @edale2's work. :P

Music still playing properly after Albrook inn with latest patch.

**Comment by Dizzy611** [comment]
Current progress: Have Terra back in party, at Narshe, getting ready to go to the sealed cave/empire base

**Comment by edale2** [comment]
> My fiancee was pretty impressed with @edale2's work. :P

*edale2 blushes*

**Comment by Dizzy611** [comment]
It's notable I'm 3/4 of the way through WoB now and have not encountered a single other instance of issue #4.

**Comment by edale2** [comment]
I'm somewhere between 1/3 and 1/2 way done with all the optional WoR content in my playthrough. with 45½ hours (!!!) of playtime on the save.

I actually have never really needed to use Inns too much in FFVI, so I haven't had the most thorough testing on that particular bug (when I want Shadow's sleep cutscenes, I usually just stay in the same Inn over and over until I get them all).

I don't recall really coming across any bugs in my playthrough that I haven't already posted about (I wasn't using the current master branch until about 3/4 through the WoB). 

The biggest thing I've found would be the audio of the wind for the "drafty room" in South Figaro's rich man's house in Locke's scenario. I'm pretty sure that particular call of the track will need special handling for the volume, since the track's worked great everywhere else it's been called (possible fix: keep that particular call of that track as SPC audio, the PCM audio isn't the best fit for that location anyways).

**Comment by Dizzy611** [comment]
I think because of that (the drafty room in south figaro) I'm going to avoid PCM for the wind effects for *now*, because I still haven't figured out a reliable way to determine what scene we're on. There has to be a memory address that tells it what set of graphics to use but I've not found it in any of the RAM maps or from experimentation in the debugger, yet. (I've been trying in order to fix #38)

**Comment by Dizzy611** [comment]
Current progress: About to finish out WoB by heading to the Floating Continent.

Encountered #4 again when revisiting Figaro with Edgar and Sabin to see the "coin flip" story sequence. So far this is the only other occurence of this issue, leading me to believe there's something unique about the way the game handles The Coin Song that causes it to not use the normal track swapping routines when swapping from it to Edgar's and Sabin's Theme

**Comment by Dizzy611** [comment]
Current progress: In WoR, have recruited: Sabin, Edgar, Setzer, Cyan, Gau.

No new bugs to report.

**Comment by edale2** [comment]
OK, I've finished all WoR content except Kefka's Tower, and the Fanatic's Tower.

That means only one thing.... Be vewy vewy qwiet... I'm hunting Cactaws (Cactars).

Desert just south of Miranda has Cactars and hoovers (slag worm in TWUE). 10 MP each, with Hoovers giving 5 MP each... and no other monsters show up there...

Maybe 1 day (possibly less) to learn all magic from all Espers, except the one from beating all 8 legendary Dragons (2 of which are in Kefka's Tower), and then a chunk of time in Dino Forest to power lvl once I can equip Espers for stat bonuses, rather than learning magic, and I'll be good to tackle the end of the game.

2, maybe 3, days until I'm done with my playthrough.

I haven't spotted any new bugs.

**Comment by Dizzy611** [comment]
Current Progress: Recruited all but Shadow (gone, forgot to save him at the end of WoB... oops), Gogo, Locke, and Mog/Umaro. Likely going for Locke next, then Mog and Umaro, then Gogo. And then I'll probably use the Colliseum to trade up some weapons, maybe do the Fanatic's Tower, and then it's Kefka time.

Good tip on the desert south of miranda. I already learned all the WoB esper magic through grinding Intangirs at triangle island before the Floating Continent but that sounds much less annoying than the Intangir grinding was.

Have notice a few odd bits where I'm not entirely sure if there's supposed to be silence or not, will have to check these against an unmodified game. I think they are supposed to be silent but they're supposed to fade gradually to silence instead of a sudden cut, because as is it's jarring. (I'm thinking specifically of stuff like, when you first meet Terra in WoR, you hear Terra's Theme (or is it Awakening? I'm not sure which it was at this point as that was hours ago :P) for a bit while she's speaking, and then it suddenly cuts to silence until you go to leave and Phunbaba attacks)

**Comment by edale2** [comment]
Traditional WoB MP grinding wisdom says to grind in Phantom Forest, on the screen with the healing lake.

A 1x ghost encounter will net you 3 MP (3x ghosts will net you 1 MP...). I find you get the 3MP encounter maybe 1/4 of the time, with 1 MP encounters 3/4 of the time.

I find a MUCH better WoB grinding location to be the first (inside cave) room of the Esper Cave (where they go after breaking out of the seal and destroying the Empire). 3 MP encounters maybe 1/2 the time, 2 MP encounters 3/8 of the time, and 1 MP encounters 1/8 of the time. MUCH faster overall spell learning rate.

Intangir pops up rarely, and the common encounters net 0 MP, so it's not as good a MP grinding place as it seems.

Have you done any rage training with Gau? He's a serious powerhouse with the right rages (especially stray cat for the wind-god-gau setup, or for any monster you just want to pelt with physicals).

**Comment by Dizzy611** [comment]
I've done a bit with Gau, yeah. He's not my favorite character to have around in general though, I'm kind of partial to an extremely magic-heavy party

I did kind of use him to keep myself alive in early game where a lot of his rages are super overpowered though.

**Comment by Dizzy611** [comment]
Current progress: Retrieved Locke, Gogo. On way to pick up Mog and Umaro and then wrap up a few sidequests and level up/MP grind a bit before hitting Kefka's Tower.

**Comment by edale2** [comment]
Oh, for MP grinding, Hoover has a nasty sandstorm counter, so wind defense helps a lot. Air Anchor Tool  (Fanatics Tower hidden room or coliseum) by Edgar or Gogo will 1-shot Hoover.

Cactaur has really high defense, but really low HP, a defense piercing attah such as Drill, Pummel, or Bum Rush one-shot it.

**Comment by Dizzy611** [comment]
I am going to end up absolutely ruining this game for myself but I kind of feel like replaying with the TWUP after I finish this playthrough (still where I was last night, I took a break for a bit). Just for enjoyment instead of beta testing, because now that I'm looking at it with a more critical eye some of the weird translations kind of stand out.

Like Atma Weapon's introduction, the way it ends with "GO!" like he's a super sentai announcer or the guy from Elite Beat Agents or something

**Comment by edale2** [comment]
Some of the Engrish lines were quite memorable ("Son of a submariner!!!") Thankfully TWUE keeps the best of those in, lol.

As far as bad translation moments...

"I met a girl" "you don't mean that witch everyone's talking about!" "she wasn't at fault." "We should help her!"

UGH!!! It's had been so long since I played an unmodded copy that I forgot how bad the original script was, lol. Been a MUCH more enjoyable playthrough than I'm used to with the TWUE script (especially as it takes care not to remove the exploits like Wind God Gau).

Speaking of Wind God Gau... If you have both tempests (there's only 2 in the game, one stolen from the boss on the minecarts as you escape from the magitech factory, the other a chest in the sealed cavern on the way to break the espers out). genji glove and merit award with both tempests equipped raging stray cat is a decently effective mii-wind-god-gau (2 attacks instead of 4), and leaves the offering up for someone better... like Setzer with Fixed Dice.

Oh, and for my playthrough, taking longer than I thought to get all the spells learned, but on the last batch of characters, so will be tackling the Fanatics Tower tonight, and will probably save Kefka's Tower for tomorrow.

**Comment by Dizzy611** [comment]
I think the worst bad translation line is Banon's throwaway line in Vector after the Esper attack. Y'know, the one where it makes it sound like he's suddenly got retrograde amnesia.

"Talking to the espers?! What?!" or something like that.

Like he hadn't been trying to do that since less than an hour into the game

**Comment by edale2** [comment]
If only Working Designs had localized it! lol.

**Comment by Dizzy611** [comment]
Current progress: Still doing some grinding and such in preparation for the final push.

**Comment by edale2** [comment]
Finished my playthrough (actually got my save AND savestate corrupted just before Kefka, so used a god-mode save to beat him and check the ending again).

All the audio tracks I've added work great, save that one issue with the wind in the Rich Man's house in South Figaro, no conflicts anywhere.

Now to just clean them up, I think the only one needing immediate attention is the fire effect, If I can't find a decent enough track, I may have to have a small fire over at my brother-in-law's house (he has a fire-pit) and record something myself.

**Comment by Dizzy611** [comment]
Current progress: Finished my preparation, acquired remaining party members, did a few sidequests, completed the Cultist's Tower. Have saved right next to Kefka's Tower in preparation for the final dungeon.

**Comment by Dizzy611** [comment]
Current progress: Done

Full playthrough complete.

Encountered bugs:

#38 #4(partial) #5(obviously)

We're now gearing up for release.
