### ISSUE TITLE
Town music playing during Shadow's dream sequence

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#73]
As reported by F-Bomb on Quimm:
http://forums.qhimm.com/index.php?topic=16077.msg256337#msg256337

I'll admit, I don't think I went through the dream sequences in ANY of my test runs...

**Comment by edale2** [comment]
F-Bomb's info:
>When I recruited Shadow in Cohlingen after Battle of Narshe, I slept straight away and the town music was still playing in the background while the 1st dream sequence was happening.

**Comment by Dizzy611** [comment]
I'll have to confirm this myself, in my playthrough I don't think I ever did much with shadow tbh.

**Comment by Dizzy611** [comment]
I need some sort of test save for this, so I can quickly confirm whether or not the fade-to-zero workaround has fixed it.

**Comment by Dizzy611** [comment]
Unfortunately the fix I thought I had for the bug turned out not to work :/

**Comment by Dizzy611** [comment]
I have a fix for this issue that's working, but it's causing a resurgence (at least, after a shadow dream) of the bug where the music is silent after sleeping at an inn. I'm considering this a decent enough compromise though since imo haunting silence is appropriate after these dreams and the music starts right up the minute you cross a zone boundary (ie, leave the inn).

**Comment by Dizzy611** [comment]
to be more detailed, the sleeping mechanics of the game require that no song other than the "nighty night" ditty be played in between sleeping and waking up, in order for the game to keep track of what song is playing. I'm specifically requesting track $00 (silence) be played during these dream sequences in order to work around this bug, and this has the unfortunate side effect of overwriting the area of RAM the routine for playing the right song after you wake up needs, with silence. I could create a whole massive kludge to try to work around this involving checking for calls to track $00 the same way I check for calls to track $51, but frankly it'd be opening up a massive can of worms.

**Comment by Dizzy611** [comment]
Fix is now working for all shadow cutscenes, with a few caveats.

First caveat: The "kids run through the city" song (or indeed, whatever theme the inn was playing) will play for a frame or two after the dream scene loads. This is unavoidable as it appears to be the load of the scene itself that is calling for the song, and my changes are to the event script after the scene is loaded.

Second caveat: See above about silence at the inns after the dreams.

Third caveat: The second shadow dream starts with a noticable, but short, delay due to having to overwrite a fairly large chunk of event code with $FDs.

**Comment by Dizzy611** [comment]
I'm probably going to close this after I get some feedback on the current IPS in the relevant branch. If it's a good enough fix for everyone so far then that's good enough for me.

**Comment by Dizzy611** [comment]
As I haven't gotten any feedback on this in a month, and it's "good enough for me", I'm closing this issue and pulling the branch.
