### ISSUE TITLE
No installer?

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#9]
I can't get this to work because there's no installer...

It looks like several of the files/scripts seem to call on "Installer.exe" But this exe isn't on the GitHub...

**Comment by edale2** [comment]
Correct me if I'm wrong, but the installer is just to apply the patch and download/convert the music, right?

I can apply the patch myself, so if a download link could be provided for the PCM files that would be generated from the "OCRemix (Various) - Balance and Ruin (OCR)" option on the installer, I should be able to run this.

**Comment by Dizzy611** [comment]
The installer is very clearly linked on the releases page. I will link it directly here:

https://github.com/Insidious611/DancingMadFF6/releases

Note the EXE file. That is the installer.

Providing you with the PCM files would be possible but there's a great deal of things the installer does as far as renaming and moving tracks in order to make them functional depending on the emulator or flash cart you are using. As such I do not and can not  support this method of install.

If you wish to create the installer yourself, it's simply a matter of running cxfreeze on the Installer.py file. Alternately, you can simply run the Installer.py file if you have python and all the prerequisite python modules installed.

**Comment by edale2** [comment]
Thank you, I only had the link to https://github.com/insidious611/DancingMadFF6 from the bitbucket page, which I got from the romhacking.net thread, and I don't actually see a way to get to that page from the link I had.

Granted, I'm a novice with GitHub, so I'm probably missing something obvious.

**Comment by Dizzy611** [comment]
The releases tab is a bit oddly placed, to be sure. I might add the
installer EXE itself to the github instead of just on the releases page but github recommends against uploading large files, and due to the libraries needing to be bundled with (since I'm
using pyqt5) it tends to be above the 20mb or so recommended limit.

**Comment by edale2** [comment]
Most projects I've grabbed from GitHub had a "releases" folder with the installers, if needed.

My selections (custom setup):
OCR for all it's available for.
SSC for Celes
OTH for Opera / Grand Finale? (any chance if an ID for that opera version, so I can look it up and check it's actually what I want?)
OST for What?
